// Whisper-supported languages (code → native name).
// Source: OpenAI Whisper language list. Codes are passed to whisper.cpp / Groq.
// Sorted alphabetically by native name at runtime via LANGUAGES.

export type LanguageCode = string;

export interface Language {
  code: LanguageCode;
  name: string;
}

// "auto" is handled separately (top of the select) — not part of LANGUAGES.
export const AUTO_LANGUAGE = "auto";

const RAW_LANGUAGES: Language[] = [
  { code: "af", name: "Afrikaans" },
  { code: "sq", name: "Shqip" },
  { code: "am", name: "አማርኛ" },
  { code: "ar", name: "العربية" },
  { code: "hy", name: "Հայերեն" },
  { code: "as", name: "অসমীয়া" },
  { code: "az", name: "Azərbaycanca" },
  { code: "ba", name: "Башҡортса" },
  { code: "eu", name: "Euskara" },
  { code: "be", name: "Беларуская" },
  { code: "bn", name: "বাংলা" },
  { code: "bs", name: "Bosanski" },
  { code: "br", name: "Brezhoneg" },
  { code: "bg", name: "Български" },
  { code: "ca", name: "Català" },
  { code: "zh", name: "中文" },
  { code: "hr", name: "Hrvatski" },
  { code: "cs", name: "Čeština" },
  { code: "da", name: "Dansk" },
  { code: "nl", name: "Nederlands" },
  { code: "en", name: "English" },
  { code: "et", name: "Eesti" },
  { code: "fo", name: "Føroyskt" },
  { code: "fi", name: "Suomi" },
  { code: "fr", name: "Français" },
  { code: "gl", name: "Galego" },
  { code: "ka", name: "ქართული" },
  { code: "de", name: "Deutsch" },
  { code: "el", name: "Ελληνικά" },
  { code: "gu", name: "ગુજરાતી" },
  { code: "ht", name: "Kreyòl Ayisyen" },
  { code: "ha", name: "Hausa" },
  { code: "haw", name: "ʻŌlelo Hawaiʻi" },
  { code: "he", name: "עברית" },
  { code: "hi", name: "हिन्दी" },
  { code: "hu", name: "Magyar" },
  { code: "is", name: "Íslenska" },
  { code: "id", name: "Bahasa Indonesia" },
  { code: "it", name: "Italiano" },
  { code: "ja", name: "日本語" },
  { code: "jw", name: "Basa Jawa" },
  { code: "kn", name: "ಕನ್ನಡ" },
  { code: "kk", name: "Қазақша" },
  { code: "km", name: "ខ្មែរ" },
  { code: "rw", name: "Kinyarwanda" },
  { code: "ko", name: "한국어" },
  { code: "lo", name: "ລາວ" },
  { code: "la", name: "Latina" },
  { code: "lv", name: "Latviešu" },
  { code: "ln", name: "Lingála" },
  { code: "lt", name: "Lietuvių" },
  { code: "lb", name: "Lëtzebuergesch" },
  { code: "mk", name: "Македонски" },
  { code: "mg", name: "Malagasy" },
  { code: "ms", name: "Bahasa Melayu" },
  { code: "ml", name: "മലയാളം" },
  { code: "mt", name: "Malti" },
  { code: "mi", name: "Te Reo Māori" },
  { code: "mr", name: "मराठी" },
  { code: "mn", name: "Монгол" },
  { code: "my", name: "မြန်မာ" },
  { code: "ne", name: "नेपाली" },
  { code: "no", name: "Norsk" },
  { code: "nn", name: "Nynorsk" },
  { code: "oc", name: "Occitan" },
  { code: "ps", name: "پښتو" },
  { code: "fa", name: "فارسی" },
  { code: "pl", name: "Polski" },
  { code: "pt", name: "Português" },
  { code: "pa", name: "ਪੰਜਾਬੀ" },
  { code: "ro", name: "Română" },
  { code: "ru", name: "Русский" },
  { code: "sa", name: "संस्कृतम्" },
  { code: "sn", name: "ChiShona" },
  { code: "sd", name: "سنڌي" },
  { code: "si", name: "සිංහල" },
  { code: "sk", name: "Slovenčina" },
  { code: "sl", name: "Slovenščina" },
  { code: "so", name: "Soomaali" },
  { code: "es", name: "Español" },
  { code: "su", name: "Basa Sunda" },
  { code: "sw", name: "Kiswahili" },
  { code: "sv", name: "Svenska" },
  { code: "tl", name: "Tagalog" },
  { code: "tg", name: "Тоҷикӣ" },
  { code: "ta", name: "தமிழ்" },
  { code: "tt", name: "Татарча" },
  { code: "te", name: "తెలుగు" },
  { code: "th", name: "ไทย" },
  { code: "bo", name: "བོད་སྐད" },
  { code: "to", name: "Lea Faka-Tonga" },
  { code: "tr", name: "Türkçe" },
  { code: "uk", name: "Українська" },
  { code: "ur", name: "اردو" },
  { code: "uz", name: "Oʻzbekcha" },
  { code: "vi", name: "Tiếng Việt" },
  { code: "cy", name: "Cymraeg" },
  { code: "yi", name: "ייִדיש" },
  { code: "yo", name: "Yorùbá" },
];

// Sorted alphabetically by native name (locale-aware, case-insensitive).
export const LANGUAGES: Language[] = [...RAW_LANGUAGES].sort((a, b) =>
  a.name.localeCompare(b.name, undefined, { sensitivity: "base" }),
);
